<?php

/**
 * @file
 * Contains io_test_module.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function io_test_module_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the io_test_module module.
    case 'help.page.io_test_module':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Modulo de prueba creado por DRUPAL CONSOLE') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function io_test_module_theme() {
  return [
    'io_test_module' => [
      'render element' => 'children',
    ],
  ];
}
